---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/sync-labels.yaml
  schedule:
    - cron: "17 4 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: 🚀 Synchronize labels with Label Blueprint
        uses: klaasnicolaas/action-label-blueprint@90f2ea1ff380df2e6c1c83f39797998f54cc97ab # v1.1.0
        with:
          labels-file: https://raw.githubusercontent.com/klaasnicolaas/.github/main/labels/python.yml
